### ISSUE TITLE
Logo proposal 

### ISSUE THREAD

**Issue by dee-y** [luchoagomezt/mp3-media#1]
Hi, i am a graphic designer. I noticed your project is without a logo. Would you mind i contribute a logo to your project? It's free if you accept.

**Comment by luchoagomezt** [comment]
Thanks, it is a great idea.  Thanks

**Comment by luchoagomezt** [comment]
I have assigned the issue to you

**Comment by luchoagomezt** [comment]
> Hi, i am a graphic designer. I noticed your project is without a logo. Would you mind i contribute a logo to your project? It's free if you accept.

It is a perfect idea.

**Comment by dee-y** [comment]
Hello, i have made a design, what do you think? Would you like any adjustments to be made in terms of colors, etc?

![mp3-media-02](https://user-images.githubusercontent.com/36637989/47355446-4b92b600-d6b9-11e8-822a-161ef3dc352a.jpg)

**Comment by luchoagomezt** [comment]
> Hello, i have made a design, what do you think? Would you like any adjustments to be made in terms of colors, etc?
> 

I like it. It is superb.  Would you like to open a pull request?

**Comment by dee-y** [comment]
Am glad you like it. Owk i will create Hd transparent versions and submit pull request.
